### PR TITLE
Making module compile at puppet 4.x

### PR DESCRIPTION
**Pull request by ITler**
Prolog:
This is my first pull request ever. If I did something wrong, please guide me to do better next time. Thanks...

2 Commits here 
1. addresses: #52 
2. Adding LOAD_PATH magic seen in official puppetdb sources (i.e. https://github.com/puppetlabs/puppetlabs-puppetdb/blob/master/lib/puppet/provider/puppetdb_conn_validator/puppet_https.rb) to ensure correct work of providers and types - addressing: http://projects.puppetlabs.com/issues/4248

Please add the changes to your module an publish them, so that I can use your module instead of maintaining my fork. (Maybe forking was wrong here... however) 

Thank you and kind regards
ITler

### CODE REVIEW

**Comment by ITler** [comment]
Addition:
A lot of specs fail (85). Obviously, I'm not a ruby pro, so maybe you could fix the specs. Sorry for that

**Comment by PeterParker** [comment]
+1 from me for the merge and release of this PR if possible.  Currently have the following in my Puppetfile:

```
mod 'glassfish',
  :git => "https://github.com/fatmcgav/fatmcgav-glassfish.git",
  :ref => "34d49b2"
```

Which works but is obviously not ideal.

@ITler -- I'm not necessarily convinced the specs are failing because of your changes.  Other PRs are failing on similar builds.  One potential issue though is that there are a lot of whitespace changes in your second commit which may make it hard for @fatmcgav to see changed functionality.

**Comment by ITler** [comment]
@PeterParker -- I agree, that failing specs are not because of my changes. Those whitespace changes just came out from atom beautifier/linter. There should be no additional hidden functional changes to the code. Hopefully, the PR gets merged shortly.

**Comment by fatmcgav** [comment]
@ITIer / @PeterParker Cheers for the nudge, and apologies I've not merged this one already. 

I'll try and get it merged and released this week. 

Gav

**Comment by fatmcgav** [comment]
@ITler / @PeterParker Have merged this change in, and fixed an additional 4.x issue with Glassfish::Install_Jars defined type.. 

Am working my way through the other open PR's, with a view of getting a release done later today... 

Gav

**Comment by ITler** [comment]
Great! Thank you

**Comment by PeterParker** [comment]
:+1: Thanks!

**Pull request merged**
